# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 90849e4d2ac42914d2fbc65807323b0a819caf2808e582eb93ae9d4e54c8007123d33f9a40142a507a3b6a953b3a9cfd2776cc3162e563dca35ccd545ac90685

test:
  secret_key_base: e4aefdb588cec44ff101b8665f642af0116d7441bc4165f39fa4a52d1c034c066579526f295043a71b1487d3c8869f46b13ebe256f6450bff80c682d2ffacde6

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
